### ISSUE TITLE
I can configure the elasticsearch exporter to use basic authentication 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1341]

**Comment by npepinpe** [comment]
I ran into the same issue with MongoDB, i.e. how to handle secrets.

Right now all configuration takes place with configuration files, which isn't ideal for storing (most likely) unencrypted secrets. 

Environment is an option, but that's a little more complicated if, say, you want to have 2 ES exporters, but they're both using the same env var. You'd need to configure which environment variable name to use I guess, e.g.:

```toml
[[exporters]]
id = "ES1"
# ...
  [exporters.args]
  userEnvVar = "ES_USERNAME_1"
  pwEnvVar = "ES_PASSWORD_1"
  # ...

[[exporters]]
id = "ES2"
# ...
  [exporters.args]
  userEnvVar = "ES_USERNAME_2"
  pwEnvVar = "ES_PASSWORD_2"
  # ...
```

I think environment variables are the most flexible in terms of plugging in to other secrets managing systems, e.g. vault or AWS parameter store. You can read those secrets when launching the instance and inject the correct environment (you could also create the config file with the correct params, but then you can't pre-packaged those files before launch I guess).
