### ISSUE TITLE
Container fail to start when DEPLOY_ON_KUBERNETES is true (+ no documentation on it)

### ISSUE THREAD

**Issue by arielb135** [zeebe-io/zeebe#2445]
While trying out Zeebe with DEPLOY_ON_KUBERNETES = true - it fails because the "HOST" variable is not defined:

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
      app: zeebe
      chart: flowing-retail-zeebe-0.1.0
      heritage: Tiller
      release: zeebe
    name: zeebe
    namespace: zeebe
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: zeebe
        release: zeebe
    template:
      metadata:
        labels:
          app: zeebe
          release: zeebe
      spec:
        containers:
        - env:
          - name: ZEEBE_LOG_LEVEL
            value: debug
          - name: DEPLOY_ON_KUBERNETES
            value: "true"
          image: camunda/zeebe:0.12.0
          imagePullPolicy: IfNotPresent
          name: zeebe
          ports:
          - containerPort: 26500
            name: http
            protocol: TCP
          resources:
            requests:
              memory: 3Gi
```
Then we fail to start:
```
+ configFile=/usr/local/zeebe/conf/zeebe.cfg.toml
++ hostname -i
+ export ZEEBE_HOST=172.31.34.227
+ ZEEBE_HOST=172.31.34.227
+ [[ true == \t\r\u\e ]]
/usr/local/bin/startup.sh: line 8: HOST: unbound variable
```
