### ISSUE TITLE
Document how to do a rolling update with k8s

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2613]
Document a recommended way of performing rolling update in k8s. It can use broker ready status #2612 for readyness probe.

**Comment by deepthidevaki** [comment]
For reference:
You can add readinessProbe in the container spec.
```
spec:
      containers:
      - name: zeebe
        image: ...
        ....
        readinessProbe:
          httpGet:
              path: /ready
              port: 9600
          initialDelaySeconds: 20
          periodSeconds: 5
```
