### ISSUE TITLE
unexpected end of JSON input from GetCustomHeadersAsMap() and GetVariablesAsMap()

### ISSUE THREAD

**Issue by thestrayed** [zeebe-io/zeebe#2706]
I got this error while trying to extract `headers` and `variables` from `job`. I use `example-4` from this [repo](https://github.com/zeebe-io/zeebe-get-started-go-client/blob/master/example-4/main.go). I notice that it's coming from `json.Unmarshal` function. I'm not 100% sure what is wrong with it. I'm fairly new to golang myself.

Here is the log from `example-4`
```bash
key:2251799813685250 workflows:<bpmnProcessId:"order-process" version:1 workflowKey:2251799813685249 resourceName:"order-process.bpmn" >
workflowKey:2251799813685249 bpmnProcessId:"order-process" version:1 workflowInstanceKey:2251799813685251
err unexpected end of JSON input
2019/06/23 14:50:24 Failed to complete job 2251799813685258
```

This is my docker-compose to start Zeebe broker, its gateway and monitor
```yaml
gateway:
  container_name: freework-zeebe-gateway
  image: camunda/zeebe:0.18.0
  environment:
    ZEEBE_LOG_LEVEL: debug
    ZEEBE_STANDALONE_GATEWAY: 'true'
    ZEEBE_GATEWAY_CONTACT_POINT: node0:26502
    ZEEBE_GATEWAY_CLUSTER_PORT: 26502
    ZEEBE_GATEWAY_CLUSTER_HOST: gateway
  ports:
    - '26500:26500'
  volumes:
    - ./gateway.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
node0:
  container_name: freework-zeebe-broker-1
  image: camunda/zeebe:0.18.0
  environment:
    ZEEBE_LOG_LEVEL: debug
    SIMPLE_MONITOR_EXPORTER_JDBC_URL: jdbc:h2:tcp://db:1521/zeebe-monitor
  ports:
    - '26600:26500'
    - '5701'
  volumes:
    - ./zeebe-simple-monitor-exporter-0.14.0.jar:/usr/local/zeebe/lib/zeebe-simple-monitor-exporter.jar
    - ./zeebe-hazelcast-exporter-0.4.0-SNAPSHOT.jar:/usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar
    - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
db:
  container_name: freework-zeebe-db
  image: oscarfonts/h2
  ports:
    - "1521:1521"
    - "81:81"
monitor:
  container_name: freework-zeebe-monitor
  image: camunda/zeebe-simple-monitor:latest
  environment:
    - spring.datasource.url=jdbc:h2:tcp://db:1521/zeebe-monitor
    - io.zeebe.monitor.connetionString=node0:26500
    - io.zeebe.monitor.hazelcast.connection=node0:5701
  ports:
    - "8080:8080"
  restart: always
```
Please let me know if I miss anything.
