### ISSUE TITLE
OAuth credential caching

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3063]
**Is your feature request related to a problem? Please describe.**

Multiple clients on the same node/application will most likely use the same client secret/ID, and will therefore be pulling the same OAuth credentials. To decrease traffic and avoid potential rate limits, caching those credentials so they are shareable in the same context (e.g. node) would be useful.

**Describe the solution you'd like**

Add a credentials cache as a YAML file on the local filesystem, default path `$HOME/.camunda/credentials` with the following format:

```yaml
---
audience:
  auth:
    credentials:
      access_token: "Token", # access token
      expires_in: 3600, # expiry in seconds
      token_type: "Bearer", # token type, most likely always Bearer
      scope: "grpc" # Optional scope
audience2: # ... more audiences
```

**Describe alternatives you've considered**

Users concerned with caching/rate limiting should authenticate through a proxy and control it themselves.

**Additional context**

Should be similar to the Java client implementation
