### ISSUE TITLE
ZEEBE_ADVERTISED_HOST doesn't work 

### ISSUE THREAD

**Issue by IcyEagle** [zeebe-io/zeebe#3283]
Hi there!

I'm deploying a Zeebe cluster in k8s with 3 nodes. We use Istio (have Envoy installed within a pod), that's why the **advertised host** feature is required to make it work.

Here is my zeebe.cfg.toml:
```
   # For more information about this configuration visit:
    [threads]
    cpuThreadCount = 1

    [network]
    host = "0.0.0.0"

    [gateway.monitoring]
    enabled = true
```

My startup.sh script
```
    #!/bin/bash -xeu

    configFile=/usr/local/zeebe/conf/zeebe.cfg.toml
    export ZEEBE_NODE_ID="${HOSTNAME##*-}"
    export ZEEBE_ADVERTISED_HOST=$(hostname -f)

    # We need to specify all brokers as contact points for partition healing to work correctly
    # https://github.com/zeebe-io/zeebe/issues/2684
    ZEEBE_CONTACT_POINTS=${HOSTNAME::-1}0.$(hostname -d):26502
    for (( i=1; i<$ZEEBE_CLUSTER_SIZE; i++ ))
    do
        ZEEBE_CONTACT_POINTS="${ZEEBE_CONTACT_POINTS},${HOSTNAME::-1}$i.$(hostname -d):26502"
    done
    export ZEEBE_CONTACT_POINTS="${ZEEBE_CONTACT_POINTS}"

    exec /usr/local/zeebe/bin/broker
```

Here is what I have:
```
➜  ~ k exec -it zeebe-cluster-0 -c zeebe-cluster ./bin/zbctl status -- --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 0.0.0.0:26501
  Broker 1 - 0.0.0.0:26501
  Broker 2 - 0.0.0.0:26501
```

My statefulset descriptor:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zeebe-cluster.fullname" . }}
  namespace: {{ include "zeebe-cluster.namespace" . }}
  labels:
{{ include "zeebe-cluster.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "zeebe-cluster.fullname" . }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      annotations:
        prometheus.io/port: "9600"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        json_logs: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.url }}:{{ .Values.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZEEBE_LOG_LEVEL
              value: info
            - name: ZEEBE_PARTITIONS_COUNT
              value: "3"
            - name: ZEEBE_CLUSTER_SIZE
              value: "3"
            - name: ZEEBE_REPLICATION_FACTOR
              value: "3"
            - name: JAVA_TOOL_OPTIONS
              value:
            {{- toYaml .Values.JavaOpts | nindent 16}}
          ports:
            - containerPort: {{ .Values.service.http.port }}
              name: http
            - containerPort: {{ .Values.service.gateway.port }}
              name: gateway
            - containerPort: {{ .Values.service.command.port }}
              name: command
            - containerPort: {{ .Values.service.internal.port }}
              name: internal
          readinessProbe:
            httpGet:
              path: {{ .Values.service.http.healthcheckPath }}
              port: http
            initialDelaySeconds: 60
            periodSeconds: 50
          livenessProbe:
            httpGet:
              path: {{ .Values.service.http.healthcheckPath }}
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
              subPath: zeebe.cfg.toml
            - name: config
              mountPath: /usr/local/zeebe/conf/log4j2.xml
              subPath: log4j2.xml
            - name: config
              mountPath: /usr/local/bin/startup.sh
              subPath: startup.sh
            - name: data
              mountPath: /usr/local/zeebe/data
      volumes:
        - name: config
          configMap:
            name: {{ include "zeebe-cluster.fullname" . }}
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
```

I use your image `comunda/zeebe:0.21.1`

**Comment by npepinpe** [comment]
Hey @IcyEagle, thanks for reporting this. I've been using Zeebe with linkerd so I'm surprised it doesn't work with Istio; admittedly I haven't tried it. But in your case it seems like the brokers are anyway not advertising the right address, as evidenced by the topology.

Can you launch your brokers with log level INFO? You can just add the env var `ZEEBE_LOG_LEVEL="info"`. It should print the parsed configuration at start up and we can see what Zeebe thinks it should be using.

**Comment by npepinpe** [comment]
I can also give you the configuration I use, maybe that can help.

Init script:
```sh
#!/usr/bin/env bash
set -eux -o pipefail

export ZEEBE_ADVERTISED_HOST=$(hostname -f)
export ZEEBE_NODE_ID=${ZEEBE_NODE_NAME##*-}

# As the number of replicas or the DNS is not obtainable from the downward API yet,
# defined them here based on conventions
replicaHost=${ZEEBE_NODE_NAME%-*}
export ZEEBE_CONTACT_POINTS=$(for ((i=0; i<${ZEEBE_CLUSTER_SIZE}; i++)); do echo -n "${replicaHost}-$i.$(hostname -d):26502,"; done)

exec /usr/local/bin/startup.sh
```

Stateful Set:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
spec:
  serviceName: broker
  replicas: 1
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
       accessModes:
         - ReadWriteOnce
       storageClassName: ssd
       resources:
         requests:
           storage: 50Gi
  template:
    spec:
      volumes:
        - name: configuration
          configMap:
            name: broker-config
            defaultMode: 0744
        - name: scripts
          configMap:
            name: broker-scripts
            defaultMode: 0755
      containers:
        - name: broker
          image: camunda/zeebe:latest
          ports:
            - containerPort: 26500
              name: gateway
            - containerPort: 26501
              name: command
            - containerPort: 26502
              name: cluster
            - containerPort: 9600
              name: monitoring
          env:
            - name: ZEEBE_CLUSTER_SIZE
              value: "1"
            - name: ZEEBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: data
              mountPath: /usr/local/zeebe/data
            - name: configuration
              mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
              subPath: zeebe.cfg.toml
            - name: configuration
              mountPath: /usr/local/zeebe/conf/log4j2.xml
              subPath: log4j2.xml
            - name: scripts
              mountPath: /usr/local/bin/init.sh
              subPath: init.sh
          command: ["/bin/sh"]
          args: ["-c", "exec tini -- /usr/local/bin/init.sh"]
          securityContext:
            capabilities:
                add: ["NET_ADMIN", "SYS_ADMIN"]
          readinessProbe:
            httpGet:
              path: /ready
              port: monitoring
            initialDelaySeconds: 20
            periodSeconds: 5
```

This is a partial config since I'm using kustomize to fill out some blanks, but this works with linkerd injected, so I would assume it would also work with istio.
