### ISSUE TITLE
Unable to recover properly after non-graceful shutdown

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3504]
**Describe the bug**

While the latest release looks stable under specific conditions, it seems non-graceful shut downs (due to Kubernetes killing the pod because it uses too much memory) seem to throw the whole cluster into an unstable state, where it can keep going for a little while but will eventually end up in a state where no work is done, and recovery is not possible any more.

**To Reproduce**

Deploy 0.22.0-alpha2 using the benchmark setup and let the broker use as much RAM as it wants (though I've seen this happen with `-XX:MaxRAMPercentage=75.0` as well), increase the load until you reach max throughput, and after some time some instances will start running out of memory, and typically k8s will kill the pod before the JVM throws OOM errors. After this, pods will restart, and then strange issues arise: #3486, #3485, #3484, possibly more.

**Expected behavior**

The cluster should be able to recover from non-graceful shut downs due to out of memory errors, or out of disk - if running out of disk space, adding more space should allow a node to recover (not always possible depending on how we deploy).

**Log/Stacktrace**
This is the k8s setup used to deploy `0.22.0-alpha2`:

<details><summary>Full Stacktrace</summary>
 <p>

```yaml
apiVersion: v1
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">

      <Properties>
        <Property name="log.path">${sys:app.home}/logs</Property>
        <Property name="log.pattern">%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{actor-name}] [%t] %-5level %logger{36} - %msg%n</Property>
      </Properties>

      <Appenders>
        <RollingRandomAccessFile name="RollingFile" fileName="${log.path}/zeebe.log"
          filePattern="${log.path}/zeebe-%d{yyyy-MM-dd}-%i.log.gz">
          <PatternLayout>
            <Pattern>${log.pattern}</Pattern>
          </PatternLayout>
          <Policies>
            <TimeBasedTriggeringPolicy/>
            <SizeBasedTriggeringPolicy size="250 MB"/>
          </Policies>
          <BurstFilter level="ERROR" rate="3" maxBurst="10"/>
        </RollingRandomAccessFile>

        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout>
            <Pattern>${log.pattern}</Pattern>
          </PatternLayout>
          <BurstFilter level="ERROR" rate="3" maxBurst="10"/>
        </Console>
      </Appenders>

      <Loggers>
        <Logger name="io.zeebe" level="${env:ZEEBE_LOG_LEVEL:-debug}"/>
        <Logger name="io.atomix" level="${env:ATOMIX_LOG_LEVEL:-warn}"/>

        <Root level="info">
          <AppenderRef ref="RollingFile" />
          <AppenderRef ref="Console" />
        </Root>
      </Loggers>
    </Configuration>
  zeebe.cfg.toml: |+
    [cluster]
    partitionsCount = 8
    replicationFactor = 3

    [threads]
    cpuThreadCount = 8
    ioThreadCount = 8

    [data]
    snapshotPeriod = "3m"
    maxSnapshots = "3"

    [backpressure]
    enabled = true

    [gateway]
    enable = false

    [monitoring]
    enabled = true

kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: bench
    component: broker
    environment: test
  name: bench-broker-config-4bfg7gctf8
---
apiVersion: v1
data:
  init.sh: |-
    #!/usr/bin/env bash
    set -eux -o pipefail

    export ZEEBE_ADVERTISED_HOST=$(hostname -f)
    export ZEEBE_NODE_ID=${ZEEBE_NODE_NAME##*-}

    # As the number of replicas or the DNS is not obtainable from the downward API yet,
    # defined them here based on conventions
    replicaHost=${ZEEBE_NODE_NAME%-*}
    export ZEEBE_CONTACT_POINTS=$(for ((i=0; i<${ZEEBE_CLUSTER_SIZE}; i++)); do echo -n "${replicaHost}-$i.$(hostname -d):26502,"; done)

    exec /usr/local/bin/startup.sh
kind: ConfigMap
metadata:
  labels:
    app: bench
    component: broker
    environment: test
  name: bench-broker-scripts-58m5g6d9m8
---
apiVersion: v1
data:
  gateway.cfg.toml: |
    [threads]
    cpuThreadCount = 2
    ioThreadCount = 2

    [gateway.cluster]
    requestTimeout = "60s"

    [gateway.monitoring]
    enabled = true
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">

      <Properties>
        <Property name="log.path">${sys:app.home}/logs</Property>
        <Property name="log.pattern">%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{actor-name}] [%t] %-5level %logger{36} - %msg%n</Property>
      </Properties>

      <Appenders>
        <RollingRandomAccessFile name="RollingFile" fileName="${log.path}/zeebe.log"
          filePattern="${log.path}/zeebe-%d{yyyy-MM-dd}-%i.log.gz">
          <PatternLayout>
            <Pattern>${log.pattern}</Pattern>
          </PatternLayout>
          <Policies>
            <TimeBasedTriggeringPolicy/>
            <SizeBasedTriggeringPolicy size="250 MB"/>
          </Policies>
          <BurstFilter level="ERROR" rate="3" maxBurst="10"/>
        </RollingRandomAccessFile>

        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout>
            <Pattern>${log.pattern}</Pattern>
          </PatternLayout>
          <BurstFilter level="ERROR" rate="3" maxBurst="10"/>
        </Console>
      </Appenders>

      <Loggers>
        <Logger name="io.zeebe" level="${env:ZEEBE_LOG_LEVEL:-debug}"/>

        <Root level="info">
          <AppenderRef ref="RollingFile" />
          <AppenderRef ref="Console" />
        </Root>
      </Loggers>
    </Configuration>
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: bench
    component: gateway
    environment: test
  name: bench-gateway-24bb7749df
---
apiVersion: v1
data:
  JAVA_TOOL_OPTIONS: -XX:+PrintFlagsFinal -XX:+HeapDumpOnOutOfMemoryError -XX:MinRAMPercentage=60.0
    -XX:MaxRAMPercentage=75.0
kind: ConfigMap
metadata:
  labels:
    app: bench
    environment: test
  name: bench-java-tool-options-k6bb72bk4g
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bench
    component: broker
    environment: test
  name: bench-broker
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 26500
  - name: monitoring
    port: 9600
  - name: cluster
    port: 26502
  publishNotReadyAddresses: true
  selector:
    app: bench
    component: broker
    environment: test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bench
    component: gateway
    environment: test
  name: bench-gateway
spec:
  ports:
  - name: grpc
    port: 26500
  - name: monitoring
    port: 9600
  selector:
    app: bench
    component: gateway
    environment: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bench
    component: gateway
    environment: test
  name: bench-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bench
      component: gateway
      environment: test
  template:
    metadata:
      labels:
        app: bench
        component: gateway
        environment: test
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          valueFrom:
            configMapKeyRef:
              key: JAVA_TOOL_OPTIONS
              name: bench-java-tool-options-k6bb72bk4g
        - name: ZEEBE_GATEWAY_CONTACT_POINT
          value: bench-broker
        - name: ZEEBE_GATEWAY_HOST
          value: 0.0.0.0
        - name: ZEEBE_LOG_LEVEL
          value: debug
        - name: ZEEBE_STANDALONE_GATEWAY
          value: "true"
        - name: ZEEBE_GATEWAY_CLUSTER_MEMBER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: camunda/zeebe:0.22.0-alpha2
        imagePullPolicy: Always
        name: gateway
        ports:
        - containerPort: 26500
          name: gateway
        - containerPort: 26502
          name: cluster
        - containerPort: 9600
          name: monitoring
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          tcpSocket:
            port: gateway
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 1Gi
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - mountPath: /usr/local/zeebe/conf/gateway.cfg.toml
          name: configuration
          subPath: gateway.cfg.toml
        - mountPath: /usr/local/zeebe/conf/log4j2.xml
          name: configuration
          subPath: log4j2.xml
      volumes:
      - configMap:
          defaultMode: 484
          name: bench-gateway-24bb7749df
        name: configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bench
    component: starter
    environment: test
  name: bench-starter
spec:
  replicas: 0
  selector:
    matchLabels:
      app: bench
      component: starter
      environment: test
  template:
    metadata:
      labels:
        app: bench
        component: starter
        environment: test
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Dapp.brokerUrl=bench-gateway:26500 -Dapp.starter.rate=100 -Dzeebe.client.requestTimeout=62000
        image: gcr.io/zeebe-io/starter:zeebe
        imagePullPolicy: Always
        name: starter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bench
    component: worker
    environment: test
  name: bench-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: bench
      component: worker
      environment: test
  template:
    metadata:
      labels:
        app: bench
        component: worker
        environment: test
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Dapp.brokerUrl=bench-gateway:26500 -Dzeebe.client.requestTimeout=62000
            -Dapp.worker.capacity=100
        image: gcr.io/zeebe-io/worker:zeebe
        imagePullPolicy: Always
        name: worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bench
    component: broker
    environment: test
  name: bench-broker
spec:
  podManagementPolicy: Parallel
  replicas: 5
  selector:
    matchLabels:
      app: bench
      component: broker
      environment: test
  serviceName: bench-broker
  template:
    metadata:
      labels:
        app: bench
        component: broker
        environment: test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - elasticsearch-master
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -c
        - exec tini -- /usr/local/bin/init.sh
        command:
        - /bin/sh
        env:
        - name: JAVA_TOOL_OPTIONS
          valueFrom:
            configMapKeyRef:
              key: JAVA_TOOL_OPTIONS
              name: bench-java-tool-options-k6bb72bk4g
        - name: ZEEBE_CLUSTER_SIZE
          value: "5"
        - name: ZEEBE_HOST
          value: 0.0.0.0
        - name: ZEEBE_LOG_LEVEL
          value: debug
        - name: ZEEBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: camunda/zeebe:0.22.0-alpha2
        imagePullPolicy: Always
        name: broker
        ports:
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: cluster
        - containerPort: 9600
          name: monitoring
        readinessProbe:
          httpGet:
            path: /ready
            port: monitoring
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          limits:
            cpu: 8
            memory: 16Gi
          requests:
            cpu: 2
            memory: 4Gi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
        volumeMounts:
        - mountPath: /usr/local/zeebe/data
          name: data
        - mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
          name: configuration
          subPath: zeebe.cfg.toml
        - mountPath: /usr/local/zeebe/conf/log4j2.xml
          name: configuration
          subPath: log4j2.xml
        - mountPath: /usr/local/bin/init.sh
          name: scripts
          subPath: init.sh
      volumes:
      - configMap:
          defaultMode: 484
          name: bench-broker-config-4bfg7gctf8
        name: configuration
      - configMap:
          defaultMode: 493
          name: bench-broker-scripts-58m5g6d9m8
        name: scripts
  volumeClaimTemplates:
  - metadata:
      labels:
        app: bench
        environment: test
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 256Gi
      storageClassName: ssd
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: bench
    component: metrics
    environment: test
    release: metrics
  name: bench-prometheus-monitor
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    port: monitoring
  selector:
    matchLabels:
      app: bench
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.22.0-alpha2
 - Configuration: see above
