### ISSUE TITLE
Topology response contains wrong host name

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#426]
When starting a broker cluster in docker containers using the following compose file the returned cluster topology contains the hostname `broker-3` twice.

#### docker-compose.yaml
```
version: '2'

services:

  broker-1:
    image: camunda/zeebe:latest
    volumes:
        - $PWD/broker-1:/usr/local/zeebe/conf
        - $PWD/volumes/broker-1:/usr/local/zeebe/bin/data

  broker-2:
    image: camunda/zeebe:latest
    volumes:
        - $PWD/broker-2:/usr/local/zeebe/conf
        - $PWD/volumes/broker-2:/usr/local/zeebe/bin/data

  broker-3:
    image: camunda/zeebe:latest
    volumes:
        - $PWD/broker-3:/usr/local/zeebe/conf
        - $PWD/volumes/broker-3:/usr/local/zeebe/bin/data

  zbctl:
    image: ubuntu:latest
    volumes:
        - $PWD/zbctl/zbctl:/bin/zbctl
        - $PWD/zbctl/examples:/etc/zeebe
    command: tail -f /dev/null
    working_dir: /etc/zeebe
```

#### Topology response
```
TopologyResponse {                                                                                                                                                                                                                                                              
    topic_leaders: [
        TopicLeader {
            host: "broker-1",
            port: 51015,
            topic_name: "default-topic",
            partition_id: 0
        },
        TopicLeader {
            host: "broker-3",
            port: 51015,
            topic_name: ".system",
            partition_id: 0
        }
    ],
    brokers: [
        SocketAddress {
            host: "broker-2",
            port: 51015
        },
        SocketAddress {
            host: "broker-3",
            port: 51015
        },
        SocketAddress {
            host: "broker-3",
            port: 51015
        }
    ]
}
```
