### ISSUE TITLE
I can't start a cluster with partitionCount one and three node cluster

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4664]
**Describe the bug**
I was not able to use the helm charts and start a three node cluster with partition count one and replication factor three.

```
# ZEEBE CFG
clusterSize: 3
partitionCount: 1
replicationFactor: 3
cpuThreadCount: 4
ioThreadCount: 4
gatewayMetrics: true
```

If I change the partition count to 3 everything works fine.

We see that the brokers can't connect to each other or at least it prints `ConnectException`'s. The broker stop at Step 6, which is the cluster service bootstrap part. 

We can see that the broker never becomes ready.
```
[zell zeebe-chaos/ ns:zeebe-chaos]$ kgpo
NAME                                         READY   STATUS    RESTARTS   AGE
elasticsearch-master-0                       1/1     Running   0          16m
elasticsearch-master-1                       1/1     Running   0          16m
elasticsearch-master-2                       1/1     Running   0          16m
zeebe-chaos-zeebe-0                          0/1     Running   0          16m
zeebe-chaos-zeebe-1                          0/1     Running   0          16m
zeebe-chaos-zeebe-2                          0/1     Running   0          16m
zeebe-chaos-zeebe-gateway-76c6cbbd95-77p8f   1/1     Running   0          16m
```

We verified that the configuration was applied to the Zeebe config and the broker prints the corresponding configuration on start.

**To Reproduce**

Run our benchmark setup with partitionCount 1.

**Expected behavior**
I can start a cluster with one partition.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
I 2020-06-04T11:35:25.463Z Bootstrap Broker-0 [4/10]: command api handler 
D 2020-06-04T11:35:25.515Z Bootstrap Broker-0 [4/10]: command api handler started in 52 ms 
I 2020-06-04T11:35:25.515Z Bootstrap Broker-0 [5/10]: subscription api 
D 2020-06-04T11:35:25.552Z Bootstrap Broker-0 [5/10]: subscription api started in 37 ms 
I 2020-06-04T11:35:25.553Z Bootstrap Broker-0 [6/10]: cluster services 
W 2020-06-04T11:35:46.196Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException 
W 2020-06-04T11:35:46.197Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException 
W 2020-06-04T11:35:49.014Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException 
W 2020-06-04T11:35:49.050Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException 
W 2020-06-04T11:35:52.312Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException 
W 2020-06-04T11:35:52.312Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException 
```

</p>
</details>

**Environment:**
 - OS: k8s
 - Zeebe Version: snapshot
 - Configuration: [e.g. exporters etc.]

**Comment by mingfang** [comment]
I'm seeing the same problem.
It only works when cluster size = partition count
This sounds like a bug

**Comment by Zelldon** [comment]
Hey @mingfang thanks for reporting. Are you using the helm charts or how do you deploy Zeebe?

**Comment by Zelldon** [comment]
Seems to work with docker-compose:

```
version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  node0:
    container_name: zeebe_broker_1
    image: camunda/zeebe:SNAPSHOT
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=0
      - ZEEBE_PARTITIONS_COUNT=1
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    ports:
      - "26500:26500"
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
  node1:
    container_name: zeebe_broker_2
    image: camunda/zeebe:SNAPSHOT
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=1
      - ZEEBE_PARTITIONS_COUNT=1
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
    depends_on:
      - node0
  node2:
    container_name: zeebe_broker_3
    image: camunda/zeebe:SNAPSHOT
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=2
      - ZEEBE_PARTITIONS_COUNT=1
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
    depends_on:
      - node1
```

**Comment by Zelldon** [comment]
I tried also with the new env variables:

```yaml 
version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  node0:
    container_name: zeebe_broker_1
    image: camunda/zeebe:SNAPSHOT
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=0
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=1
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    ports:
      - "26500:26500"
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
  node1:
    container_name: zeebe_broker_2
    image: camunda/zeebe:SNAPSHOT
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=1
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=1
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
    depends_on:
      - node0
  node2:
    container_name: zeebe_broker_3
    image: camunda/zeebe:SNAPSHOT
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=2
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=1
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
    depends_on:
      - node1
```

We test in integration tests with partition one and cluster size 3. For me it looks like we doing something wrong in the helm charts :thinking:
