### ISSUE TITLE
Failed weekly benchmark after a little over 24 hours

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4807]
**Describe the bug**

I started a standard benchmark on 2020-06-22 at night, and on 2020-06-24 around midnight or 1am it ran out of disk space, and has not recovered since then. Namespace is `snapshot-20200622`. You can look at all the errors that occurred by looking at the Error Reporting for zeebe-broker and zeebe-gateway with the service version `snapshot-20200622`. 

Two errors occurred that were unexpected:

1. NullPointException (https://console.cloud.google.com/errors/CMnI1sSGr8atxAE?service=zeebe-broker&version=snapshot-20200622&time=P1D&project=zeebe-io) (link to issue https://github.com/zeebe-io/zeebe/issues/4806)
1. BufferOverflowException (https://console.cloud.google.com/errors/CK62_IPX_6nzIg?service=zeebe-broker&version=snapshot-20200622&time=P1D&project=zeebe-io)

No particular errors occurred after, but note that one broker ran out of disk space, and another is very close to do so.

**To Reproduce**

Here is the Helm chart values used for the benchmark; everything else is the normal stuff.

<details><summary>zeebe-values.yml</summary>

```yaml
image:
  repository: gcr.io/zeebe-io/zeebe
  tag: SNAPSHOT-20200622
  pullPolicy: Always

# ZEEBE CFG
clusterSize: 3
partitionCount: 3
replicationFactor: 3
cpuThreadCount: 4
ioThreadCount: 4
gatewayMetrics: true

podSecurityContext:
  capabilities:
        add: ["NET_ADMIN"]

gateway:
  replicas: 1
  logLevel: debug
  env:
    - name: ZEEBE_LOG_APPENDER
      value: Stackdriver
    - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
      value: zeebe-gateway
    - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: ATOMIX_LOG_LEVEL
      value: INFO
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
      value: "4"

# Uncomment to add custom YAML configuration
# This will overwrite anything at the application.yml location
# zeebeCfg: {}

# JavaOpts:
# DEFAULTS
JavaOpts: >
  -Xmx4g
  -Xms4g
  -XX:+ExitOnOutOfMemoryError
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
  -Xlog:gc*:file=/usr/local/zeebe/data/gc.log:time:filecount=7,filesize=8M

# Environment variables
env:
  # Enable JSON logging for google cloud stackdriver
  - name: ZEEBE_LOG_APPENDER
    value: Stackdriver
  - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
    value: zeebe-broker
  - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  # Avoid tons of noise when exporting larger payloads
  - name: JAVA_OPTS
    value: >-
      -Dzeebe.broker.exporters.elasticsearch.args.index.ignoreVariablesAbove=32767
  - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
    value: "true"
  - name: ATOMIX_LOG_LEVEL
    value: INFO

# RESOURCES
resources:
  limits:
    cpu: 5
    memory: 12Gi
  requests:
    cpu: 5
    memory: 12Gi

# PVC
pvcAccessMode: ["ReadWriteOnce"]
pvcSize: 128Gi
pvcStorageClassName: ssd


# ELASTIC
elasticsearch:
  enabled: true
  imageTag: 6.8.5

  replicas: 3
  minimumMasterNodes: 2

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "ssd"
    resources:
      requests:
        storage: 300Gi

  esJavaOpts: "-Xmx4g -Xms4g"

  resources:
    requests:
      cpu: 3
      memory: 8Gi
    limits:
      cpu: 3
      memory: 8Gi

# KIBANA
kibana:
  enabled: false

# PROMETHEUS
prometheus:
  enabled: false

  servicemonitor:
    enabled: true
```

</details>

Run `make zeebe`, wait until all pods are ready, then run `make worker starter`. Not sure how reproducible this is however, so it looks like doing a post-mortem will be more useful.

**Expected behavior**

My benchmark can run stable and happy like the alpha2 one which has been running for over a month :exploding_head: 

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.24.0-SNAPSHOT of 2020-06-22
 - Configuration: benchmark config + the values above
