### ISSUE TITLE
Expose RocksDB column family options as configuration

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#5279]
**Is your feature request related to a problem? Please describe.**

Based on my system, I would like to configure RocksDB column family options to optimize the performance.

**Describe the solution you'd like**

I would like to be able to configure all column family options using the Zeebe configuration.

**Describe alternatives you've considered**

I cannot change the options except I patch Zeebe and build my own version.

**Additional context**

RocksDB column family options can be read from a properties string https://github.com/facebook/rocksdb/blob/cd4592c22031c42ee23a5edf2cfcdf44e99f7f6f/java/src/main/java/org/rocksdb/ColumnFamilyOptions.java#L97, so we could allow the user to just pass a multiline string instead of exposing every option ourself.

**Comment by menski** [comment]
We have to check how to handle our default values with this approach

**Comment by korthout** [comment]
Configuration will be available under:
```
zeebe:
  broker:
    data:
      rocksdb:
        columnFamilyOptions:
          # example options:
          compaction_pri: "kOldestSmallestSeqFirst"
          write_buffer_size: 67108864
```
Please look in RocksDB's SCM repo for the files: `cf_options.h` and `options_helper.cc` to find all available key names and corresponding values.
