### ISSUE TITLE
Missing docs for advertisedHost and advertisedPort configuration

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5419]
**Description**

We can configure advertisedHost and advertisedPort for commandApi, monitoringApi and internalApi. But this is not documented here https://docs.zeebe.io/appendix/broker-config-template.html.

**Comment by devil-cyber** [comment]
Hey @deepthidevaki can you provide some more details I would like to work on this issue

**Comment by deepthidevaki** [comment]
@devil-cyber Thank you for your interest in contributing to the project.

Currently setting the advertised host and port for commandApi and internalApi is broken See https://github.com/zeebe-io/zeebe/issues/5426#issuecomment-699877638 . So I would suggest to wait until that issue is resolved before we update the docs.

Assuming it works well, you can set the advertised port for commandApi and internalApi as follows. 
```
network:
      host: 0.0.0.0

      commandApi:
        advertisedHost: 1.1.1.1
        advertisedPort: 1111
      internalApi:
        advertisedHost: 2.2.2.2
        advertisedPort: 2222

```
For the documentation you can add the above fields to `dist/src/main/broker.standalone.yaml.template` and `dist/src/main/broker.yaml.template`.
