### ISSUE TITLE
How can I add a new broker to the zeebe cluster ?

### ISSUE THREAD

**Issue by yzhengwei** [zeebe-io/zeebe#6061]
My Zeebe cluster has 3 nodes, it has been running for a while, now I want to add 2 new nodes to the cluster, how do I add 2 new node into the broker to the Zeebe cluster?

```yaml
zeebe:
  broker:
    stepTimeout: 5m
    gateway:
      enable: true
      network:
        port: 26500
        minKeepAliveInterval: 30s
      cluster:
        requestTimeout: 15s
      threads:
        managementThreads: 2000
      monitoring:
        enabled: true
      longPolling:
        enabled: true
    network:
      portOffset: 0
      maxMessageSize: 4MB
      commandApi:
        host: 10.21.95.56
        port: 26501
      internalApi:
        host: 10.21.95.56
        port: 26502
      monitoringApi:
        port: 10106
    data:
      directories: [ /data/zeebe ]
      logSegmentSize: 512MB
      snapshotPeriod: 15m
    cluster:
      nodeId: 2
      partitionsCount: 3
      replicationFactor: 3
      clusterSize: 3
      initialContactPoints: [ 10.21.88.54:26502, 10.21.88.16:26502, 10.21.95.56:26502 ]
      clusterName: zeebe-cluster
      membership:
        broadcastUpdates: false
        broadcastDisputes: true
        notifySuspect: false
        gossipInterval: 250ms
        gossipFanout: 2
        probeInterval: 1s
        probeTimeout: 2s
        suspectProbes: 3
        failureTimeout: 10s
        syncInterval: 10s
    threads:
      cpuThreadCount: 2
      ioThreadCount: 2
    backpressure:
      enabled : true
      algorithm: "vegas"
      vegas:
        initialLimit: 20
        alpha: 3
        beta: 6
    exporters:
      elasticsearch:
        className: io.zeebe.exporter.ElasticsearchExporter
        args:
          url: http://prod.zeebe.sbos.sg2.es:9200
          bulk:
            delay: 5
            size: 1000
            memoryLimit: 10485760
          index:
            prefix: ms
            createTemplate: true
            command: false
            event: true
            rejection: false
            deployment: true
            error: true
            incident: true
            job: true
            jobBatch: false
            message: false
            messageSubscription: false
            variable: true
            variableDocument: true
            workflowInstance: true
            workflowInstanceCreation: false
            workflowInstanceSubscription: false
```
