### ISSUE TITLE
How do I set the number of replicas with index in my Zeebe Elasticsearch cluster?

### ISSUE THREAD

**Issue by yzhengwei** [zeebe-io/zeebe#6086]
I found that on my Zeebe Elasticsearch cluster, some indexes have a replicas number of 0,  which is very dangerous, How do I customize the number of primary and replica sharding of indexes ?
Here is my configuration of elasticsearch in the zeebe:
```yaml

    exporters:
      elasticsearch:
        className: io.zeebe.exporter.ElasticsearchExporter
        args:
          url: http://prod.zeebe.sbos.sg2.es:9200
          bulk:
            delay: 5
            size: 1000
            memoryLimit: 10485760
          index:
            prefix: ms
            createTemplate: true
            command: false
            event: true
            rejection: false
            deployment: true
            error: true
            incident: true
            job: true
            jobBatch: false
            message: false
            messageSubscription: false
            variable: true
            variableDocument: true
            workflowInstance: true
            workflowInstanceCreation: false
            workflowInstanceSubscription: false

```

![image](https://user-images.githubusercontent.com/59439277/104088741-e03a5c00-52a3-11eb-910d-2cd79a2ebff1.png)
